cc=gcc

all : ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16 ex17 ex18 

ex8: ex8.c
	$(cc) -o ex8 ex8.c

ex8: ex8.c
	$(cc) -o ex8 ex8.c

ex9: ex9.c
	$(cc) -o ex9 ex9.c

ex10: ex10.c
	$(cc) -o ex10 ex10.c

ex11: ex11.c
	$(cc) -o ex11 ex11.c

ex12: ex12.c
	$(cc) -o ex12 ex12.c

ex13: ex13.c
	$(cc) -o ex13 ex13.c

ex14: ex14.c
	$(cc) -o ex14 ex14.c

ex15: ex15.c
	$(cc) -o ex15 ex15.c

ex16: ex16.c
	$(cc) -o ex16 ex16.c

ex17: ex17.c
	$(cc) -o ex17 ex17.c

ex18: ex18.c
	$(cc) -o ex18 ex18.c